### ISSUE TITLE
Filtering Listed Spaces by Date

### ISSUE THREAD

**Issue by chriswhitehouse** [ZeenLamDev/MakersBnB#18]

**Comment by PiperS52** [comment]
completed and merged

**Comment by chriswhitehouse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user So i can see spaces in a specified date range I would like to be able to filter the list by date of availibility.](https://trello.com/c/qhvRsHBj/8-as-a-user-so-i-can-see-spaces-in-a-specified-date-range-i-would-like-to-be-able-to-filter-the-list-by-date-of-availibility)
